### ISSUE TITLE
Use CSS variables instead of SCSS variables

### ISSUE THREAD

**Issue by larsdouweschuitema** [larsdouweschuitema/minor-realtimeweb#2]
SCSS:
```SCSS
$font-stack: 'system-ui';
```

CSS:
```CSS
:root {
--font-stack: system-ui;
}
```
